In [1]:
import pandas as pd
import pysam
import os

In [2]:
# mutations
mut_path = "/home/ubuntu/honors_research/peak_align/phased_haplotype_muts/merged_unique_variants.bed"
mutations = pd.read_csv(mut_path, sep="\t", header=None)
mutations.columns = ["chrom", "start", "end"]
mutations

       chrom     start       end
0       chr1     86377     86378
1       chr1    139232    139233
2       chr1    817185    817186
3       chr1    825766    825767
4       chr1    905372    905373
...      ...       ...       ...
193019  chrY  56823143  56823144
193020  chrY  56823146  56823147
193021  chrY  56858714  56858715
193022  chrY  56862954  56862955
193023  chrY  56873829  56873830

[193024 rows x 3 columns]

In [4]:
#nucleosomes
def load_nuc1(nuc_path):
    colnames = ["chr", "start", "end", "NAME", "col5", "col6", "col7", "col8", "phase"]
    df = pd.read_csv(nuc_path, sep="\t", header=None)
    df.columns = colnames
    return df

def load_nuc2(nuc_path):
    colnames = ["chr", "start", "end", "NAME", "col5", "col6", "col7", "col8", "col9", "col10", "col11", "col12", "col13", "col14", "col15", "col16", "col17","phase"]
    df = pd.read_csv(nuc_path, sep="\t", header=None)
    df.columns = colnames
    return df

In [5]:
#plusone nucs
plusone_nuc_phase0 = load_nuc1("/home/ubuntu/honors_research/peak_align/reference_files/+1_Nuc_References/+1_phase0_250bp.bed")
plusone_nuc_phase1 = load_nuc1("/home/ubuntu/honors_research/peak_align/reference_files/+1_Nuc_References/+1_phase1_250bp.bed")
plusone_nuc_phase2 = load_nuc1("/home/ubuntu/honors_research/peak_align/reference_files/+1_Nuc_References/+1_phase2_250bp.bed")
plusone_nuc_phase3 = load_nuc1("/home/ubuntu/honors_research/peak_align/reference_files/+1_Nuc_References/+1_phase3_250bp.bed")
plusone_nuc_phase4 = load_nuc1("/home/ubuntu/honors_research/peak_align/reference_files/+1_Nuc_References/+1_phase4_250bp.bed")
plusone_nuc_phase5 = load_nuc1("/home/ubuntu/honors_research/peak_align/reference_files/+1_Nuc_References/+1_phase5_250bp.bed")
plusone_nuc_phase6 = load_nuc1("/home/ubuntu/honors_research/peak_align/reference_files/+1_Nuc_References/+1_phase6_250bp.bed")
plusone_nuc_phase7 = load_nuc1("/home/ubuntu/honors_research/peak_align/reference_files/+1_Nuc_References/+1_phase7_250bp.bed")
plusone_nuc_phase8 = load_nuc1("/home/ubuntu/honors_research/peak_align/reference_files/+1_Nuc_References/+1_phase8_250bp.bed")
plusone_nuc_phase9 = load_nuc1("/home/ubuntu/honors_research/peak_align/reference_files/+1_Nuc_References/+1_phase9_250bp.bed")
plusone_nuc = pd.concat([plusone_nuc_phase0, plusone_nuc_phase1, plusone_nuc_phase2, plusone_nuc_phase3, plusone_nuc_phase4, plusone_nuc_phase5, plusone_nuc_phase6, plusone_nuc_phase7, plusone_nuc_phase8, plusone_nuc_phase9], ignore_index=True)

#plustwo nucs
plustwo_nuc_phase0 = load_nuc2("/home/ubuntu/honors_research/peak_align/reference_files/+2_Nuc_References/+2_phase0_250bp.bed")
plustwo_nuc_phase1 = load_nuc2("/home/ubuntu/honors_research/peak_align/reference_files/+2_Nuc_References/+2_phase1_250bp.bed")
plustwo_nuc_phase2 = load_nuc2("/home/ubuntu/honors_research/peak_align/reference_files/+2_Nuc_References/+2_phase2_250bp.bed")
plustwo_nuc_phase3 = load_nuc2("/home/ubuntu/honors_research/peak_align/reference_files/+2_Nuc_References/+2_phase3_250bp.bed")
plustwo_nuc_phase4 = load_nuc2("/home/ubuntu/honors_research/peak_align/reference_files/+2_Nuc_References/+2_phase4_250bp.bed")
plustwo_nuc_phase5 = load_nuc2("/home/ubuntu/honors_research/peak_align/reference_files/+2_Nuc_References/+2_phase5_250bp.bed")
plustwo_nuc_phase6 = load_nuc2("/home/ubuntu/honors_research/peak_align/reference_files/+2_Nuc_References/+2_phase6_250bp.bed")
plustwo_nuc_phase7 = load_nuc2("/home/ubuntu/honors_research/peak_align/reference_files/+2_Nuc_References/+2_phase7_250bp.bed")
plustwo_nuc_phase8 = load_nuc2("/home/ubuntu/honors_research/peak_align/reference_files/+2_Nuc_References/+2_phase8_250bp.bed")
plustwo_nuc_phase9 = load_nuc2("/home/ubuntu/honors_research/peak_align/reference_files/+2_Nuc_References/+2_phase9_250bp.bed")
plustwo_nuc = pd.concat([plustwo_nuc_phase0, plustwo_nuc_phase1, plustwo_nuc_phase2, plustwo_nuc_phase3, plustwo_nuc_phase4, plustwo_nuc_phase5, plustwo_nuc_phase6, plustwo_nuc_phase7, plustwo_nuc_phase8, plustwo_nuc_phase9], ignore_index=True)

In [6]:
# peak align files - plusone (phases 0 to 9)
phase0_plusone = pd.read_csv("/home/ubuntu/honors_research/peak_align/+1_Nuc_Aligns/gnomAD_+1_phase0_250bp_Output.cdt", sep="\t")
phase1_plusone = pd.read_csv("/home/ubuntu/honors_research/peak_align/+1_Nuc_Aligns/gnomAD_+1_phase1_250bp_Output.cdt", sep="\t")
phase2_plusone = pd.read_csv("/home/ubuntu/honors_research/peak_align/+1_Nuc_Aligns/gnomAD_+1_phase2_250bp_Output.cdt", sep="\t")
phase3_plusone = pd.read_csv("/home/ubuntu/honors_research/peak_align/+1_Nuc_Aligns/gnomAD_+1_phase3_250bp_Output.cdt", sep="\t")
phase4_plusone = pd.read_csv("/home/ubuntu/honors_research/peak_align/+1_Nuc_Aligns/gnomAD_+1_phase4_250bp_Output.cdt", sep="\t")
phase5_plusone = pd.read_csv("/home/ubuntu/honors_research/peak_align/+1_Nuc_Aligns/gnomAD_+1_phase5_250bp_Output.cdt", sep="\t")
phase6_plusone = pd.read_csv("/home/ubuntu/honors_research/peak_align/+1_Nuc_Aligns/gnomAD_+1_phase6_250bp_Output.cdt", sep="\t")
phase7_plusone = pd.read_csv("/home/ubuntu/honors_research/peak_align/+1_Nuc_Aligns/gnomAD_+1_phase7_250bp_Output.cdt", sep="\t")
phase8_plusone = pd.read_csv("/home/ubuntu/honors_research/peak_align/+1_Nuc_Aligns/gnomAD_+1_phase8_250bp_Output.cdt", sep="\t")
phase9_plusone = pd.read_csv("/home/ubuntu/honors_research/peak_align/+1_Nuc_Aligns/gnomAD_+1_phase9_250bp_Output.cdt", sep="\t")

# peak align files - plustwo (phases 0 to 9)
phase0_plustwo = pd.read_csv("/home/ubuntu/honors_research/peak_align/+2_Nuc_Aligns/gnomAD_+2_phase0_250bp_Output.cdt", sep="\t")
phase1_plustwo = pd.read_csv("/home/ubuntu/honors_research/peak_align/+2_Nuc_Aligns/gnomAD_+2_phase1_250bp_Output.cdt", sep="\t")
phase2_plustwo = pd.read_csv("/home/ubuntu/honors_research/peak_align/+2_Nuc_Aligns/gnomAD_+2_phase2_250bp_Output.cdt", sep="\t")
phase3_plustwo = pd.read_csv("/home/ubuntu/honors_research/peak_align/+2_Nuc_Aligns/gnomAD_+2_phase3_250bp_Output.cdt", sep="\t")
phase4_plustwo = pd.read_csv("/home/ubuntu/honors_research/peak_align/+2_Nuc_Aligns/gnomAD_+2_phase4_250bp_Output.cdt", sep="\t")
phase5_plustwo = pd.read_csv("/home/ubuntu/honors_research/peak_align/+2_Nuc_Aligns/gnomAD_+2_phase5_250bp_Output.cdt", sep="\t")
phase6_plustwo = pd.read_csv("/home/ubuntu/honors_research/peak_align/+2_Nuc_Aligns/gnomAD_+2_phase6_250bp_Output.cdt", sep="\t")
phase7_plustwo = pd.read_csv("/home/ubuntu/honors_research/peak_align/+2_Nuc_Aligns/gnomAD_+2_phase7_250bp_Output.cdt", sep="\t")
phase8_plustwo = pd.read_csv("/home/ubuntu/honors_research/peak_align/+2_Nuc_Aligns/gnomAD_+2_phase8_250bp_Output.cdt", sep="\t")
phase9_plustwo = pd.read_csv("/home/ubuntu/honors_research/peak_align/+2_Nuc_Aligns/gnomAD_+2_phase9_250bp_Output.cdt", sep="\t")


# merging all peak align files into one big df
plusone_phases_peak_aligns = [phase0_plusone, phase1_plusone, phase2_plusone, phase3_plusone, phase4_plusone, phase5_plusone, phase6_plusone, phase7_plusone, phase8_plusone, phase9_plusone]
plustwo_phases_peak_aligns = [phase0_plustwo, phase1_plustwo, phase2_plustwo, phase3_plustwo, phase4_plustwo, phase5_plustwo, phase6_plustwo, phase7_plustwo, phase8_plustwo, phase9_plustwo]

plusone_merged_peak_aligns = pd.concat(plusone_phases_peak_aligns)
plustwo_merged_peak_aligns = pd.concat(plustwo_phases_peak_aligns)

In [7]:
plustwo_merged_peak_aligns

,NAME,0,1,2,3,4,5,6,7,8,...,240,241,242,243,244,245,246,247,248,249
0,chr1_2229073_2229073,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,chr1_3857730_3857730,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,chr1_6393995_6393995,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,chr1_9234225_9234225,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,chr1_11011982_11011982,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4576,chr9_93096676_93096676,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4577,chr9_129024363_129024363,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4578,chrX_103554656_103554656,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4579,chrX_119333906_119333906,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4580,chrX_154411126_154411126,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [8]:
def nuc_phases(peak_aligns):

    # based on "NAME" (CHR_start_end) column -> take out each chr and start information
    # then with start, do start -125 -> set start-125 as a new column "start"
    # drop the NAME column, leaving just chr and "start" at the beginning of the dataframe, followed by the rest of the columns from the phases dataframe
    
    # Split the 'NAME' column into 'chr', 'start', and 'end'
    peak_aligns[['chr', 'start', 'end']] = peak_aligns['NAME'].str.split('_', expand=True)

    # Convert 'start' to integer and adjust it by subtracting 125
    peak_aligns['start'] = peak_aligns['start'].astype(int) - 125

    # Drop the 'NAME' column
    peak_aligns = peak_aligns.drop(columns=['NAME'])

    # Reorder columns to place 'chr' and 'start' at the beginning
    reordered_columns = ['chr', 'start'] + [col for col in peak_aligns.columns if col not in ['chr', 'start', 'end']]
    peak_aligns = peak_aligns[reordered_columns]

    return peak_aligns



    # merged_phases = pd.merge(phases, nucleosomes[["chr", "start", "NAME"]], 
    #               on="NAME", how="left")
    # #print(merged_phases.head())
    
    # # move chrom and start after NAME
    # merged_phases = merged_phases[["chr", "start", "NAME"] + list(merged_phases.columns[1:-2])]

    # # dropping NAME column
    # merged_phases = merged_phases.drop(columns=["NAME"])

    # return merged_phases

plusone_merged_phases = nuc_phases(plusone_merged_peak_aligns)
plustwo_merged_phases = nuc_phases(plustwo_merged_peak_aligns)
plusone_merged_phases

,chr,start,0,1,2,3,4,5,6,7,...,240,241,242,243,244,245,246,247,248,249
0,chr1,999519,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,chr1,1013484,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,chr1,1020605,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,chr1,1185393,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,chr1,1231741,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4681,chrX,154479022,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4682,chrX,154547338,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4683,chrX,154801829,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4684,chrX,154805624,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4685,chrX,155880983,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [10]:
columns_to_select = []
for col in range(plusone_merged_phases.shape[1]):
    if (col) % 10 == 0:  # Check if the column index minus 4 is a multiple of 10
        columns_to_select.extend([col+1, col+2, col + 3])
columns_to_select

# Ensure column indices are valid (within bounds)
columns_to_select = [col for col in columns_to_select if 0 <= col < plusone_merged_phases.shape[1]]

# selecting first column + columns to select
exposed_plusone = plusone_merged_phases.iloc[:, [0] + columns_to_select]

# filter out rows where all selected columns are 0
exposed_plusone = exposed_plusone[exposed_plusone.iloc[:, 2:].sum(axis=1) != 0] 
exposed_plusone

,chr,start,0,1,9,10,11,19,20,21,...,219,220,221,229,230,231,239,240,241,249
7,chr1,1305991,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
44,chr1,12619750,0,0,0,0,0,0,0,0,...,0,0,0,0,1,1,0,0,0,0
68,chr1,21632508,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
112,chr1,28235687,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
138,chr1,33350098,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4528,chr9,134066663,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4538,chr9,136645906,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4623,chrX,68433905,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4650,chrX,119685608,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4664,chrX,135892259,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [11]:
# create unexposed columns by selecting the rest of the columns not in columns_to_select
all_columns = set(range(plusone_merged_phases.shape[1]))
unexposed_columns = list(all_columns - set(columns_to_select))

# ensure column indices are valid (within bounds)
unexposed_columns = [col for col in unexposed_columns if 0 <= col < plusone_merged_phases.shape[1]]
unexposed_columns = unexposed_columns[1:]

# select the first two columns + unexposed columns - ensuring proper column selection
unexposed_plusone = plusone_merged_phases.iloc[:, [0, 1] + unexposed_columns]


# filter out rows where all selected columns are 0
unexposed_plusone = unexposed_plusone[unexposed_plusone.iloc[:, 2:].sum(axis=1) != 0]
unexposed_plusone

,chr,start,2,3,4,5,6,7,8,12,...,236,237,238,242,243,244,245,246,247,248
6,chr1,1274011,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,1,0,0,0
7,chr1,1305991,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
31,chr1,9657416,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
32,chr1,9943479,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
44,chr1,12619750,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4608,chrX,52921371,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1
4647,chrX,118503811,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4648,chrX,118557542,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4650,chrX,119685608,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4664,chrX,135892259,0,0,0,0,0,0,0,0,...,0,1,1,0,0,0,0,0,0,0

In [12]:
columns_to_select = []
for col in range(plustwo_merged_phases.shape[1]):
    if (col) % 10 == 0:  # Check if the column index minus 4 is a multiple of 10
        columns_to_select.extend([col+1, col+2, col + 3])
columns_to_select

# Ensure column indices are valid (within bounds)
columns_to_select = [col for col in columns_to_select if 0 <= col < plustwo_merged_phases.shape[1]]

# selecting first column + columns to select
exposed_plustwo = plustwo_merged_phases.iloc[:, [0] + columns_to_select]

# filter out rows where all selected columns are 0
exposed_plustwo = exposed_plustwo[exposed_plustwo.iloc[:, 2:].sum(axis=1) != 0] 

# create unexposed columns by selecting the rest of the columns not in columns_to_select
all_columns = set(range(plustwo_merged_phases.shape[1]))
unexposed_columns = list(all_columns - set(columns_to_select))

# ensure column indices are valid (within bounds)
unexposed_columns = [col for col in unexposed_columns if 0 <= col < plustwo_merged_phases.shape[1]]
unexposed_columns = unexposed_columns[1:]

# select the first two columns + unexposed columns - ensuring proper column selection
unexposed_plustwo = plustwo_merged_phases.iloc[:, [0, 1] + unexposed_columns]


# filter out rows where all selected columns are 0
unexposed_plustwo = unexposed_plustwo[unexposed_plustwo.iloc[:, 2:].sum(axis=1) != 0]

In [13]:
def positions_from_matrix(df):
    """Return set of (chrom, pos) where df has non‑zero values."""
    pos_set = set()
    for _, row in df.iterrows():
        chrom = row.iloc[0]
        start = int(row.iloc[1])
        for col in row.index[2:]:
            value = row[col]
            if value != 0:
                offset = int(col)          # your columns are numeric offsets
                pos = start + offset 
                pos_set.add((chrom, pos))
    return pos_set

# build sets of exposed and unexposed positions
exposed_pos_plusone  = positions_from_matrix(exposed_plusone)
unexposed_pos_plusone = positions_from_matrix(unexposed_plusone)
exposed_pos_plustwo = positions_from_matrix(exposed_plustwo)
unexposed_pos_plustwo = positions_from_matrix(unexposed_plustwo)

In [18]:
plusone_filtered_mutations = mutations.copy()
plusone_filtered_mutations["exposed"] = "none"  # default value

accum_exposed = 0
accum_unexposed = 0

for idx, row in plusone_filtered_mutations.iterrows():
    key = (row["chrom"], row["start"])
    if key in exposed_pos_plusone:
        plusone_filtered_mutations.at[idx, "exposed"] = "exposed"
        accum_exposed += 1
    elif key in unexposed_pos_plusone:
        plusone_filtered_mutations.at[idx, "exposed"] = "unexposed"
        accum_unexposed += 1
    # else: stays "none" (never seen in either matrix)

print("Total exposed:", accum_exposed)
print("Total unexposed:", accum_unexposed)
print(plusone_filtered_mutations.groupby("exposed").size())

Total exposed: 871
Total unexposed: 1947
exposed
exposed         871
none         190206
unexposed      1947
dtype: int64

In [16]:
plustwo_filtered_mutations = mutations.copy()
plustwo_filtered_mutations["exposed"] = "none"  # default value

accum_exposed = 0
accum_unexposed = 0

for idx, row in plustwo_filtered_mutations.iterrows():
    key = (row["chrom"], row["start"])
    if key in exposed_pos_plustwo:
        plustwo_filtered_mutations.at[idx, "exposed"] = "exposed"
        accum_exposed += 1
    elif key in unexposed_pos_plustwo:
        plustwo_filtered_mutations.at[idx, "exposed"] = "unexposed"
        accum_unexposed += 1
    # else: stays "none" (never seen in either matrix)

print("Total exposed:", accum_exposed)
print("Total unexposed:", accum_unexposed)
print(plustwo_filtered_mutations.groupby("exposed").size())

Total exposed: 892
Total unexposed: 2044
exposed
exposed         892
none         190088
unexposed      2044
dtype: int64

In [19]:
#filtering out "none"

plusone_filtered_mutations = plusone_filtered_mutations[plusone_filtered_mutations["exposed"] != "none"]
plustwo_filtered_mutations = plustwo_filtered_mutations[plustwo_filtered_mutations["exposed"] != "none"]

Adding the mutational context

In [21]:
# loading vcf files
folder_path = '/home/ubuntu/honors_research/vcf_files'
vcf_files = [os.path.join(folder_path, file) for file in os.listdir(folder_path) if file.endswith('.vcf.gz')]

variant_set = set()
for vcf_file in vcf_files:
    vcf = pysam.VariantFile(vcf_file)
    for record in vcf:
        variant_old = f"{record.chrom}:{record.pos}:{record.ref}>{','.join(record.alts)}"
        chr_name, pos, mutation = variant_old.split(':')
        ref, alt = mutation.split(">")
        

#chr1	86374	86375	A>AT

        pos_start = int(pos) -1

        # Filter out insertions and deletions (ref and alt lengths must be equal)
        if (len(ref) > 1) or  (len(alt) > 1):
            continue

        pos_start = int(pos) - 1
        pos_end = int(pos) + len(ref) - 1
            
            
            

        variant = f"{record.chrom}:{pos_start}:{pos_end}:{record.ref}>{','.join(record.alts)}"

        variant_set.add(variant)


    # create a dataframe (with chrom, pos, ref>alt columns -> 3 in total)
vcf_df = pd.DataFrame(list(variant_set), columns=["variant"])
vcf_df["chrom"] = vcf_df["variant"].apply(lambda x: x.split(":")[0])
vcf_df["start"] = vcf_df["variant"].apply(lambda x: int(x.split(":")[1]))
vcf_df["end"] = vcf_df["variant"].apply(lambda x: int(x.split(":")[2]))
vcf_df["ref_alt"] = vcf_df["variant"].apply(lambda x: x.split(":")[3])
vcf_df = vcf_df[["chrom", "start", "end", "ref_alt"]]
vcf_df
#variant_set

[W::hts_idx_load3] The index file is older than the data file: /home/ubuntu/honors_research/vcf_files/28815_output.g.vcf.gz.tbi
[W::hts_idx_load3] The index file is older than the data file: /home/ubuntu/honors_research/vcf_files/28814_output.g.vcf.gz.tbi
[W::hts_idx_load3] The index file is older than the data file: /home/ubuntu/honors_research/vcf_files/28812_output.g.vcf.gz.tbi
[W::hts_idx_load3] The index file is older than the data file: /home/ubuntu/honors_research/vcf_files/28813_output.g.vcf.gz.tbi
[W::hts_idx_load3] The index file is older than the data file: /home/ubuntu/honors_research/vcf_files/28816_output.g.vcf.gz.tbi

        chrom      start        end ref_alt
0        chr4  183759315  183759316     T>G
1       chr15   57256621   57256622     A>C
2       chr12   44105661   44105662     G>C
3       chr11  106077385  106077386     G>A
4       chr17   59623219   59623220     G>A
...       ...        ...        ...     ...
215229  chr12  103855896  103855897     G>A
215230   chr7   87154043   87154044     C>A
215231   chr7   22051309   22051310     G>A
215232   chr5  173056019  173056020     A>C
215233  chr17   42422262   42422263     A>G

[215234 rows x 4 columns]

In [22]:
merged_plusone_muts_df = plusone_filtered_mutations.merge(
    vcf_df[["chrom", "start", "end", "ref_alt"]],  # Select only relevant columns from vcf_df
    on=["chrom", "start", "end"],  # Match on chrom, start, and end
    how="left"  # Use a left join to keep all rows from mutations
)

merged_plustwo_muts_df = plustwo_filtered_mutations.merge(
    vcf_df[["chrom", "start", "end", "ref_alt"]],  # Select only relevant columns from vcf_df
    on=["chrom", "start", "end"],  # Match on chrom, start, and end
    how="left"  # Use a left join to keep all rows from mutations
)

In [23]:
# removing duplicates
merged_plusone_muts_nodups = merged_plusone_muts_df.drop_duplicates(subset=['chrom', 'start', 'end'])
merged_plustwo_muts_nodups = merged_plustwo_muts_df.drop_duplicates(subset=['chrom', 'start', 'end'])

In [26]:
import pysam

def add_context_column(df, reference_genome_path):
    """
    Adds a 'context' column to the DataFrame with the nucleotide context (before, SNP, after).

    Parameters:
    df (pd.DataFrame): DataFrame containing mutation information with 'chrom', 'start', and 'end' columns (0-based).
    reference_genome_path (str): Path to the reference genome (e.g., hg38.fa.gz).

    Returns:
    pd.DataFrame: Updated DataFrame with a new 'context' column.
    """
    # Load the reference genome
    fasta = pysam.FastaFile(reference_genome_path)

    # Function to fetch context for a single mutation
    def fetch_context(row):
        try:
            chrom = row['chrom']
            pos = row['start'] + 1  # Convert 0-based to 1-based for pysam
            ref = fasta.fetch(chrom, pos - 1, pos)  # Reference nucleotide at the SNP position
            before = fasta.fetch(chrom, pos - 2, pos - 1)  # Nucleotide before
            after = fasta.fetch(chrom, pos, pos + 1)  # Nucleotide after

            # Making everything in caps
            before = before.upper()
            ref = ref.upper()
            after = after.upper()


            return f"{before}{ref}{after}"
        except KeyError:
            # Handle cases where the chromosome is not found in the reference genome
            return "Context not found"

    # Apply the fetch_context function to each row in the DataFrame
    df['context'] = df.apply(fetch_context, axis=1)

    return df

In [27]:
add_context_column(merged_plustwo_muts_nodups, "/home/ubuntu/honors_research/hg38.fa")
add_context_column(merged_plusone_muts_nodups, "/home/ubuntu/honors_research/hg38.fa")
#mismatched_mutations = merged_df_nodups[merged_df_nodups.apply(lambda row: row['ref_alt'][0] != row['context'][1], axis=1)]
#matched_mutations = merged_df_nodups[merged_df_nodups.apply(lambda row: row['ref_alt'][0] == row['context'][1], axis=1)]

/tmp/ipykernel_531581/2568215511.py:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['context'] = df.apply(fetch_context, axis=1)
/tmp/ipykernel_531581/2568215511.py:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['context'] = df.apply(fetch_context, axis=1)

     chrom      start        end    exposed ref_alt context
0     chr1     940471     940472  unexposed     T>C     TTT
1     chr1    1069576    1069577  unexposed     G>A     GGT
2     chr1    1069599    1069600  unexposed     G>A     CGC
3     chr1    1274158    1274159  unexposed     C>A     CCG
4     chr1    1274255    1274256  unexposed     A>G     CAG
...    ...        ...        ...        ...     ...     ...
2815  chrX  120485955  120485956  unexposed     C>T     TCA
2816  chrX  120486277  120486278  unexposed     C>T     GCC
2817  chrX  129961869  129961870    exposed     A>C     CAA
2818  chrX  153583154  153583155  unexposed     G>A     TGA
2819  chrX  154763182  154763183  unexposed     C>T     ACT

[2817 rows x 6 columns]

In [28]:
#export
merged_plusone_muts_nodups.to_csv("/home/ubuntu/honors_research/exposed_muts_plusone.csv", index=False)
merged_plustwo_muts_nodups.to_csv("/home/ubuntu/honors_research/exposed_muts_plustwo.csv", index=False)