In [2]:
import pandas as pd
from scipy.stats import chisquare

In [9]:
# positive control

data = {
    "col1_0": [90, 0, 0],
    "col2_1": [0, 5, 0],
    "col3_2": [0, 0, 5],
    "col4_3": [0, 0, 0],
    "col5_4": [0, 0, 0],
    "col6_5": [0, 0, 0],
    "col7_6": [0, 0, 0],
    "col8_7": [0, 0, 0],
    "col9_8": [0, 0, 0],
    "col10_9": [0, 0, 0],
}
peak_align = pd.DataFrame(data)


# create empty dictionary for conting table
contingency_table = {f'+{i}': 0 for i in range(10)}

# loop through columns in peak_align df -> get sum for each column + add to dictionary
for col in peak_align.columns:
    # getting the last digit of the column name  (e.g., "11" -> 1)
    position = int(col[-1]) 
    
    # sum the values in the column and add to the corresponding position
    contingency_table[f'+{position}'] += peak_align[col].sum()

# convert the dictionary to a dataframe
contingency_table_df = pd.DataFrame([contingency_table])

# expected data (uniform distribution)
total = contingency_table_df.sum().sum() 
num_categories = len(contingency_table_df.columns)
expected = [total / num_categories] * num_categories  

# Perform the Chi-Square test
chi2_stat, p_value = chisquare(contingency_table_df.values[0], expected)


print(f"Chi-Square Statistic: {chi2_stat}")
print(f"P-value: {p_value}")

# Interpretation
if p_value < 0.05:
    print("Significant result: The test is working as expected.")
else:
    print("Non-significant result: Check the implementation.")

Chi-Square Statistic: 715.0
P-value: 4.1191286065757155e-148
Significant result: The test is working as expected.

In [20]:
# trial run - using phase0 of ucsc snps x haining's second set of columns
path = "/home/ubuntu/honors_research/peak_align/ucsc_muts/phase0_ucsc_2_250bp.cdt"
peak_align = pd.read_csv(path, sep="\t")

peak_align_no_name = peak_align.drop(columns = ["NAME"])

# create empty dictionary for conting table
contingency_table = {f'+{i}': 0 for i in range(10)}

# loop through columns in peak_align df -> get sum for each column + add to dictionary
for col in peak_align_no_name.columns:
    # getting the last digit of the column name  (e.g., "11" -> 1)
    position = int(col[-1]) 
    
    # sum the values in the column and add to the corresponding position
    contingency_table[f'+{position}'] += peak_align_no_name[col].sum()

# convert the dictionary to a dataframe
contingency_table_df = pd.DataFrame([contingency_table])

# expected data (uniform distribution)
total = contingency_table_df.sum().sum() 
num_categories = len(contingency_table_df.columns)
expected = [total / num_categories] * num_categories  


chi2_stat, p_value = chisquare(contingency_table_df.values[0], expected)

print(f"Chi-Square Statistic: {chi2_stat}")
print(f"P-value: {p_value}")

Chi-Square Statistic: 1.6677415639755848
P-value: 0.9957005822284133

In [18]:
expected

[np.float64(103.3),
 np.float64(103.3),
 np.float64(103.3),
 np.float64(103.3),
 np.float64(103.3),
 np.float64(103.3),
 np.float64(103.3),
 np.float64(103.3),
 np.float64(103.3),
 np.float64(103.3)]

In [3]:
# import the peak align output files
path = "/home/ubuntu/honors_research/peak_align/ucsc_snps_edited_TSS_all_adj+1Nuc_1_250bp_Output.cdt"
peak_align = pd.read_csv(path, sep="\t")
peak_align = peak_align.drop(columns = ["YORF"])

In [4]:
peak_align

,NAME,0,1,2,3,4,5,6,7,8,...,240,241,242,243,244,245,246,247,248,249
0,chr1_21782419_21782419,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,chr16_68085718_68085718,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,chr1_148634329_148634329,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,chr1_156747365_156747365,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,chr1_172449989_172449989,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4158,chr6_29486584_29486584,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4159,chr6_31703415_31703415,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4160,chr6_32167960_32167960,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4161,chr6_37176059_37176059,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4162,chr7_106569825_106569825,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [5]:
# jsut do one of them as an exmaple
# for chi-square: chi-square test on each base pair in a period (i.e., make a contingency table with columns for 0bp, +1bp, ... +9bp)
peak_align_no_name = peak_align.drop(columns = ["NAME"])

# create a contignency table for each base pair position in a period (e.g. 0bp is all columns that end in 0)

In [6]:
# create empty dictionary for conting table
contingency_table = {f'+{i}': 0 for i in range(10)}

# loop through columns in peak_align df -> get sum for each column + add to dictionary
for col in peak_align_no_name.columns:
    # getting the last digit of the column name  (e.g., "11" -> 1)
    position = int(col[-1]) 
    
    # sum the values in the column and add to the corresponding position
    contingency_table[f'+{position}'] += peak_align_no_name[col].sum()

# convert the dictionary to a dataframe
contingency_table_df = pd.DataFrame([contingency_table])

In [7]:
contingency_table_df

    +0   +1   +2   +3   +4   +5   +6   +7   +8   +9
0  726  733  697  715  735  735  723  711  720  703

In [8]:
# expected data (uniform distribution)
total = contingency_table_df.sum().sum() 
num_categories = len(contingency_table_df.columns)
expected = [total / num_categories] * num_categories  
expected = pd.DataFrame([expected])
expected

       0      1      2      3      4      5      6      7      8      9
0  719.8  719.8  719.8  719.8  719.8  719.8  719.8  719.8  719.8  719.8

In [9]:
# chi square testing goodness of fit test
from scipy.stats import chisquare

chi2_stat, p_value = chisquare(contingency_table_df.values[0], expected.values[0])

print(f"Chi-Square Statistic: {chi2_stat}")
print(f"P-value: {p_value}")

Chi-Square Statistic: 2.205612670186163
P-value: 0.9877830863202776

Chi-Square Testing for UCSC X Haining's Second set of columns

In [10]:
# import the peak align output files
path_2 = "/home/ubuntu/honors_research/peak_align/ucsc_snps_edited_TSS_all_adj+1Nuc_2_250bp_Output.cdt"
peak_align_2 = pd.read_csv(path, sep="\t")
peak_align_2 = peak_align_2.drop(columns = ["YORF"])

peak_align_2_no_name = peak_align_2.drop(columns = ["NAME"])

# create empty dictionary for conting table
contingency_table_2 = {f'+{i}': 0 for i in range(10)}

# loop through columns in peak_align df -> get sum for each column + add to dictionary
for col in peak_align_2_no_name.columns:
    # getting the last digit of the column name  (e.g., "11" -> 1)
    position = int(col[-1]) 
    
    # sum the values in the column and add to the corresponding position
    contingency_table_2[f'+{position}'] += peak_align_2_no_name[col].sum()

# convert the dictionary to a dataframe
contingency_table_df_2 = pd.DataFrame([contingency_table_2])

# expected data (uniform distribution)
total_2 = contingency_table_df_2.sum().sum() 
num_categories_2 = len(contingency_table_df_2.columns)
expected_2 = [total_2 / num_categories_2] * num_categories_2  


chi2_stat_2, p_value_2 = chisquare(contingency_table_df_2.values[0], expected_2)

print(f"Chi-Square Statistic: {chi2_stat_2}")
print(f"P-value: {p_value_2}")

Chi-Square Statistic: 2.205612670186163
P-value: 0.9877830863202776

Chi-Square Testing for UCSC X Haining's third set of columns

In [11]:
# import the peak align output files
path_3 = "/home/ubuntu/honors_research/peak_align/ucsc_snps_edited_TSS_all_adj+1Nuc_3_250bp_Output.cdt"
peak_align_3 = pd.read_csv(path, sep="\t")
peak_align_3 = peak_align_3.drop(columns = ["YORF"])

peak_align_3_no_name = peak_align_3.drop(columns = ["NAME"])

# create empty dictionary for conting table
contingency_table_3 = {f'+{i}': 0 for i in range(10)}

# loop through columns in peak_align df -> get sum for each column + add to dictionary
for col in peak_align_3_no_name.columns:
    # getting the last digit of the column name  (e.g., "11" -> 1)
    position = int(col[-1]) 
    
    # sum the values in the column and add to the corresponding position
    contingency_table_3[f'+{position}'] += peak_align_3_no_name[col].sum()

# convert the dictionary to a dataframe
contingency_table_df_3 = pd.DataFrame([contingency_table_3])

# expected data (uniform distribution)
total_3 = contingency_table_df_3.sum().sum() 
num_categories_3 = len(contingency_table_df_3.columns)
expected_3 = [total_3 / num_categories_3] * num_categories_3  


chi2_stat_3, p_value_3 = chisquare(contingency_table_df_3.values[0], expected_3)

print(f"Chi-Square Statistic: {chi2_stat_3}")
print(f"P-value: {p_value_3}")

Chi-Square Statistic: 2.205612670186163
P-value: 0.9877830863202776

Chi-Square Testing for UCSC X Haining's fourth set of columns

In [14]:
# import the peak align output files
path_4 = "/home/ubuntu/honors_research/peak_align/ucsc_snps_edited_TSS_all_adj+1Nuc_4_250bp_Output.cdt"
peak_align_4 = pd.read_csv(path, sep="\t")
peak_align_4 = peak_align_4.drop(columns = ["YORF"])

peak_align_4_no_name = peak_align_4.drop(columns = ["NAME"])

# create empty dictionary for conting table
contingency_table_4 = {f'+{i}': 0 for i in range(10)}

# loop through columns in peak_align df -> get sum for each column + add to dictionary
for col in peak_align_4_no_name.columns:
    # getting the last digit of the column name  (e.g., "11" -> 1)
    position = int(col[-1]) 
    
    # sum the values in the column and add to the corresponding position
    contingency_table_4[f'+{position}'] += peak_align_4_no_name[col].sum()

# convert the dictionary to a dataframe
contingency_table_df_4 = pd.DataFrame([contingency_table_4])

# expected data (uniform distribution)
total_4 = contingency_table_df_4.sum().sum() 
num_categories_4 = len(contingency_table_df_4.columns)
expected_4 = [total_4 / num_categories_4] * num_categories_4  


chi2_stat_4, p_value_4 = chisquare(contingency_table_df_4.values[0], expected_4)

print(f"Chi-Square Statistic: {chi2_stat_4}")
print(f"P-value: {p_value_4}")

Chi-Square Statistic: 2.205612670186163
P-value: 0.9877830863202776

PEGR Mutations X Haining's first set of columns

In [15]:
path = "/home/ubuntu/honors_research/peak_align/phased_haplotype_muts/merged_unique_variants_edited_TSS_all_adj+1Nuc_250bp_Output.cdt"
peak_align = pd.read_csv(path, sep="\t")
peak_align = peak_align.drop(columns = ["YORF"])

peak_align_no_name = peak_align.drop(columns = ["NAME"])

# create empty dictionary for conting table
contingency_table = {f'+{i}': 0 for i in range(10)}

# loop through columns in peak_align df -> get sum for each column + add to dictionary
for col in peak_align_no_name.columns:
    # getting the last digit of the column name  (e.g., "11" -> 1)
    position = int(col[-1]) 
    
    # sum the values in the column and add to the corresponding position
    contingency_table[f'+{position}'] += peak_align_no_name[col].sum()

# convert the dictionary to a dataframe
contingency_table_df = pd.DataFrame([contingency_table])

# expected data (uniform distribution)
total = contingency_table_df.sum().sum() 
num_categories = len(contingency_table_df.columns)
expected = [total / num_categories] * num_categories 


chi2_stat, p_value = chisquare(contingency_table_df.values[0], expected)

print(f"Chi-Square Statistic: {chi2_stat}")
print(f"P-value: {p_value}")

Chi-Square Statistic: 20.941932807963504
P-value: 0.012910757775478853

In [16]:
expected

[np.float64(964.4),
 np.float64(964.4),
 np.float64(964.4),
 np.float64(964.4),
 np.float64(964.4),
 np.float64(964.4),
 np.float64(964.4),
 np.float64(964.4),
 np.float64(964.4),
 np.float64(964.4)]

In [17]:
contingency_table_df.values[0]

array([ 899,  920,  983, 1058, 1023,  943,  962,  968,  951,  937])